#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

count_files() {
  find "$1" -maxdepth 1 -type f -name "$2" | wc -l | tr -d ' '
}

stage0_pass="$(count_files tests/conformance/stage0/pass '*.jda')"
stage0_fail="$(count_files tests/conformance/stage0/fail '*.jda')"
stage1_pass="$(count_files tests/conformance/stage1/pass '*.jda')"
stage1_fail="$(count_files tests/conformance/stage1/fail '*.jda')"

mkdir -p docs

cat > docs/CONFORMANCE_STATUS.md <<EOF
# Conformance Status

This file is generated by \`tools/dev/generate_docs.sh\`.
Do not edit manually.

## Test Inventory
- Stage 0 pass cases: ${stage0_pass}
- Stage 0 fail cases: ${stage0_fail}
- Stage 1 pass cases: ${stage1_pass}
- Stage 1 fail cases: ${stage1_fail}

## Commands
- Run Stage 0 smoke: \`make ci-stage0\`
- Run Stage 0 conformance: \`make ci-stage0-conformance\`
- Run Stage 1 conformance: \`make ci-stage1-conformance\`
- Run all quality checks: \`make quality\`

## Notes
- Stage 1 conformance target is scaffolding and will skip until Stage 1 compiler binary is available.
- Keep fixture counts and this generated file in sync by running \`make docs\`.
EOF

echo "[docs] generated docs/CONFORMANCE_STATUS.md"
