#!/usr/bin/env python3
"""Generate a machine-readable index of the Jda standard library.

Writes JSON describing every stdlib package and the declarations it exports, so
a tool or model can resolve a function signature without grepping 139 files.

Usage:
    python3 tools/jda-index.py [--output docs/stdlib-index.json] [--check]

--check regenerates into memory and exits non-zero if the committed file is
stale, for use as a CI gate.
"""

import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STDLIB = os.path.join(ROOT, "stdlib")

FN_RE = re.compile(r"^fn\s+([A-Za-z_]\w*)\s*\((.*?)\)\s*(?:->\s*(.+?))?\s*\{", re.S)
STRUCT_RE = re.compile(r"^struct\s+([A-Za-z_]\w*)")
ENUM_RE = re.compile(r"^enum\s+([A-Za-z_]\w*)")
TRAIT_RE = re.compile(r"^trait\s+([A-Za-z_]\w*)")
CONST_RE = re.compile(r"^const\s+([A-Za-z_]\w*)\s*=\s*(.+?)\s*$")


def split_params(raw):
    """Split a parameter list on commas that are not nested in <> or ()."""
    params, depth, cur = [], 0, ""
    for ch in raw:
        if ch in "<(":
            depth += 1
        elif ch in ">)":
            depth -= 1
        if ch == "," and depth == 0:
            params.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        params.append(cur.strip())

    out = []
    for p in params:
        if ":" in p:
            name, _, typ = p.partition(":")
            out.append({"name": name.strip(), "type": typ.strip()})
        else:
            out.append({"name": p.strip(), "type": None})
    return out


def parse_file(path):
    with open(path, encoding="utf-8", errors="replace") as fh:
        lines = fh.read().split("\n")

    pkg = {"functions": [], "structs": [], "enums": [], "traits": [], "consts": []}
    for i, line in enumerate(lines):
        lineno = i + 1
        m = FN_RE.match(line)
        if m:
            pkg["functions"].append({
                "name": m.group(1),
                "params": split_params(m.group(2)),
                "returns": (m.group(3) or "").strip() or None,
                "line": lineno,
            })
            continue
        for regex, key in ((STRUCT_RE, "structs"), (ENUM_RE, "enums"), (TRAIT_RE, "traits")):
            m = regex.match(line)
            if m:
                pkg[key].append({"name": m.group(1), "line": lineno})
                break
        else:
            m = CONST_RE.match(line)
            if m:
                pkg["consts"].append({"name": m.group(1), "value": m.group(2), "line": lineno})
    return pkg


def build():
    packages = []
    for fname in sorted(os.listdir(STDLIB)):
        if not fname.endswith(".jda"):
            continue
        path = os.path.join(STDLIB, fname)
        pkg = parse_file(path)
        pkg["name"] = fname[:-4]
        pkg["path"] = "stdlib/" + fname
        pkg["include"] = "--include stdlib/" + fname
        packages.append(pkg)

    return {
        "schema": 1,
        "note": "Generated by tools/jda-index.py. Do not edit by hand.",
        "package_count": len(packages),
        "function_count": sum(len(p["functions"]) for p in packages),
        "packages": packages,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", default=os.path.join(ROOT, "docs", "stdlib-index.json"))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    index = build()
    text = json.dumps(index, indent=2, sort_keys=False) + "\n"

    if args.check:
        if not os.path.exists(args.output):
            print("[jda-index] FAIL: %s does not exist" % args.output)
            return 1
        with open(args.output, encoding="utf-8") as fh:
            if fh.read() != text:
                print("[jda-index] FAIL: %s is stale; run: python3 tools/jda-index.py" % args.output)
                return 1
        print("[jda-index] PASS: index is current")
        return 0

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("[jda-index] wrote %s (%d packages, %d functions)"
          % (args.output, index["package_count"], index["function_count"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
