#!/usr/bin/env python3
"""
Auto-generated jda0 specification from jda1.jda constants and structures.

DO NOT EDIT MANUALLY - regenerate using:
  python3 tools/generate_jda0_spec.py bootstrap/stage1/jda1.jda tools/jda0_spec.py
"""

# Token type constants
TOKENS = {
    'TOK_AMP': 32,
    'TOK_AND': 37,
    'TOK_ARROW': 22,
    'TOK_COLON': 20,
    'TOK_COMMA': 19,
    'TOK_CONST': 39,
    'TOK_DOT': 33,
    'TOK_ELSE': 3,
    'TOK_EOF': 40,
    'TOK_EQ': 23,
    'TOK_EQEQ': 24,
    'TOK_F64': 44,
    'TOK_FATARROW': 34,
    'TOK_FN': 0,
    'TOK_GT': 27,
    'TOK_GTE': 35,
    'TOK_I32': 42,
    'TOK_I64': 41,
    'TOK_I8': 43,
    'TOK_IDENT': 10,
    'TOK_IF': 2,
    'TOK_INT': 11,
    'TOK_LBRACE': 15,
    'TOK_LBRACK': 17,
    'TOK_LET': 1,
    'TOK_LOOP': 4,
    'TOK_LPAREN': 13,
    'TOK_LT': 26,
    'TOK_LTE': 36,
    'TOK_MATCH': 7,
    'TOK_MINUS': 29,
    'TOK_NEQ': 25,
    'TOK_OR': 38,
    'TOK_PLUS': 28,
    'TOK_PRINT': 8,
    'TOK_RBRACE': 16,
    'TOK_RBRACK': 18,
    'TOK_RET': 5,
    'TOK_RPAREN': 14,
    'TOK_SEMI': 21,
    'TOK_SLASH': 31,
    'TOK_STAR': 30,
    'TOK_STR': 12,
    'TOK_STRUCT': 6,
    'TOK_SYSCALL': 9,
}

# Type constants
TYPES = {
    'TYPE_F64': 4,
    'TYPE_I32': 2,
    'TYPE_I64': 1,
    'TYPE_I8': 3,
    'TYPE_PTR': 5,
    'TYPE_PTR_FLAG': 0x10000,
    'TYPE_PTR_I32': 0x10002,
    'TYPE_PTR_I64': 0x10001,
    'TYPE_PTR_I8': 0x10003,
    'TYPE_VOID': 0,
}

# Opcode constants
OPCODES = {
    'OP_ADD': 1,
    'OP_ADDR': 23,
    'OP_ALLOC': 26,
    'OP_AND': 12,
    'OP_BR': 15,
    'OP_CALL': 17,
    'OP_CMP_EQ': 6,
    'OP_CMP_GT': 9,
    'OP_CMP_GTE': 10,
    'OP_CMP_LT': 8,
    'OP_CMP_LTE': 11,
    'OP_CMP_NE': 7,
    'OP_CONST': 0,
    'OP_DIV': 4,
    'OP_JMP': 16,
    'OP_LOAD': 22,
    'OP_LOAD_MEM': 24,
    'OP_MUL': 3,
    'OP_NEG': 5,
    'OP_OR': 13,
    'OP_PRINT_INT': 27,
    'OP_RET': 14,
    'OP_STORE': 21,
    'OP_STORE_MEM': 25,
    'OP_STRLEN': 20,
    'OP_STRLIT': 19,
    'OP_SUB': 2,
    'OP_SYSCALL': 18,
}

# Structure definitions with field offsets
STRUCTURES = {
    'BasicBlock': {
        'size': 536,
        'fields': {
            'id': {'offset': 0, 'size': 8, 'type': 'i64'},
            'instrs': {'offset': 8, 'size': 512, 'type': 'Instr[64]'},
            'instr_cnt': {'offset': 520, 'size': 8, 'type': 'i64'},
            'label_off': {'offset': 528, 'size': 8, 'type': 'i64'},
        }
    },
    'ConstVal': {
        'size': 12,
        'fields': {
            'found': {'offset': 0, 'size': 4, 'type': 'i32'},
            'val': {'offset': 4, 'size': 8, 'type': 'i64'},
        }
    },
    'Fixup': {
        'size': 32,
        'fields': {
            'code_off': {'offset': 0, 'size': 8, 'type': 'i64'},
            'target_bb': {'offset': 8, 'size': 8, 'type': 'i64'},
            'kind': {'offset': 16, 'size': 8, 'type': 'i64'},
            'str_len': {'offset': 24, 'size': 8, 'type': 'i64'},
        }
    },
    'Instr': {
        'size': 92,
        'fields': {
            'op': {'offset': 0, 'size': 4, 'type': 'i32'},
            'itype': {'offset': 4, 'size': 4, 'type': 'i32'},
            'id': {'offset': 8, 'size': 8, 'type': 'i64'},
            'dead': {'offset': 16, 'size': 4, 'type': 'i32'},
            'operand0': {'offset': 20, 'size': 8, 'type': 'i64'},
            'operand1': {'offset': 28, 'size': 8, 'type': 'i64'},
            'operand2': {'offset': 36, 'size': 8, 'type': 'i64'},
            'operand3': {'offset': 44, 'size': 8, 'type': 'i64'},
            'imm': {'offset': 52, 'size': 8, 'type': 'i64'},
            'str_start': {'offset': 60, 'size': 8, 'type': 'i64'},
            'str_len': {'offset': 68, 'size': 8, 'type': 'i64'},
            'bb_target0': {'offset': 76, 'size': 8, 'type': 'i64'},
            'bb_target1': {'offset': 84, 'size': 8, 'type': 'i64'},
        }
    },
    'JirFunction': {
        'size': 1345,
        'fields': {
            'src': {'offset': 0, 'size': 1, 'type': '&i8'},
            'src_len': {'offset': 1, 'size': 8, 'type': 'i64'},
            'blocks': {'offset': 9, 'size': 512, 'type': 'BasicBlock[64]'},
            'block_cnt': {'offset': 521, 'size': 8, 'type': 'i64'},
            'vars': {'offset': 529, 'size': 256, 'type': 'VarEntry[32]'},
            'var_cnt': {'offset': 785, 'size': 8, 'type': 'i64'},
            'next_slot_off': {'offset': 793, 'size': 8, 'type': 'i64'},
            'next_id': {'offset': 801, 'size': 8, 'type': 'i64'},
            'strtab': {'offset': 809, 'size': 512, 'type': 'i8[512]'},
            'strtab_pos': {'offset': 1321, 'size': 8, 'type': 'i64'},
            'stab': {'offset': 1329, 'size': 8, 'type': '&StructTable'},
            'param_cnt': {'offset': 1337, 'size': 8, 'type': 'i64'},
        }
    },
    'LowerCtx': {
        'size': 26640,
        'fields': {
            'ra': {'offset': 0, 'size': 8, 'type': 'RegAlloc'},
            'fixups': {'offset': 8, 'size': 8192, 'type': 'Fixup[1024]'},
            'fix_cnt': {'offset': 8200, 'size': 8, 'type': 'i64'},
            'bb_offsets': {'offset': 8208, 'size': 2048, 'type': 'i64[256]'},
            'use_cnt': {'offset': 10256, 'size': 16384, 'type': 'i32[4096]'},
        }
    },
    'Node': {
        'size': 88,
        'fields': {
            'node_type': {'offset': 0, 'size': 4, 'type': 'i32'},
            'op': {'offset': 4, 'size': 4, 'type': 'i32'},
            'imm': {'offset': 8, 'size': 8, 'type': 'i64'},
            'data_type': {'offset': 16, 'size': 4, 'type': 'i32'},
            'param_cnt': {'offset': 20, 'size': 4, 'type': 'i32'},
            'child_cnt': {'offset': 24, 'size': 4, 'type': 'i32'},
            'ret_type': {'offset': 28, 'size': 4, 'type': 'i32'},
            'token': {'offset': 32, 'size': 8, 'type': 'i64'},
            'token2': {'offset': 40, 'size': 8, 'type': 'i64'},
            'child0': {'offset': 48, 'size': 8, 'type': '&Node'},
            'child1': {'offset': 56, 'size': 8, 'type': '&Node'},
            'child2': {'offset': 64, 'size': 8, 'type': '&Node'},
            'child3': {'offset': 72, 'size': 8, 'type': '&Node'},
            'children': {'offset': 80, 'size': 8, 'type': 'i64'},
        }
    },
    'RegAlloc': {
        'size': 49256,
        'fields': {
            'pool': {'offset': 0, 'size': 32, 'type': 'i32[8]'},
            'val2reg': {'offset': 32, 'size': 16384, 'type': 'i32[4096]'},
            'reg2val': {'offset': 16416, 'size': 64, 'type': 'i64[8]'},
            'spill_off': {'offset': 16480, 'size': 32768, 'type': 'i64[4096]'},
            'sp_top': {'offset': 49248, 'size': 8, 'type': 'i64'},
        }
    },
    'StructTable': {
        'size': 133648,
        'fields': {
            'cnt': {'offset': 0, 'size': 8, 'type': 'i64'},
            'names': {'offset': 8, 'size': 512, 'type': 'i64[64]'},
            'nlens': {'offset': 520, 'size': 512, 'type': 'i64[64]'},
            'fcnts': {'offset': 1032, 'size': 512, 'type': 'i64[64]'},
            'sizes': {'offset': 1544, 'size': 512, 'type': 'i64[64]'},
            'fbases': {'offset': 2056, 'size': 512, 'type': 'i64[64]'},
            'field_cnt': {'offset': 2568, 'size': 8, 'type': 'i64'},
            'fnames': {'offset': 2576, 'size': 32768, 'type': 'i64[4096]'},
            'flens': {'offset': 35344, 'size': 32768, 'type': 'i64[4096]'},
            'foffs': {'offset': 68112, 'size': 32768, 'type': 'i64[4096]'},
            'fowners': {'offset': 100880, 'size': 32768, 'type': 'i64[4096]'},
        }
    },
    'Token': {
        'size': 28,
        'fields': {
            'type': {'offset': 0, 'size': 4, 'type': 'i32'},
            'str_start': {'offset': 4, 'size': 8, 'type': 'i64'},
            'str_len': {'offset': 12, 'size': 8, 'type': 'i64'},
            'imm': {'offset': 20, 'size': 8, 'type': 'i64'},
        }
    },
    'VarEntry': {
        'size': 32,
        'fields': {
            'name_start': {'offset': 0, 'size': 8, 'type': 'i64'},
            'name_len': {'offset': 8, 'size': 8, 'type': 'i64'},
            'slot_off': {'offset': 16, 'size': 8, 'type': 'i64'},
            'stype': {'offset': 24, 'size': 8, 'type': 'i64'},
        }
    },
}

# All constants (for reference)
ALL_CONSTANTS = {
    'NODE_ADDR': 18,
    'NODE_ARRAY_ALLOC': 19,
    'NODE_BINOP': 5,
    'NODE_BLOCK': 10,
    'NODE_CALL': 4,
    'NODE_DEREF': 21,
    'NODE_FIELD': 12,
    'NODE_FIELD_STORE': 16,
    'NODE_FN': 0,
    'NODE_IDENT': 6,
    'NODE_IF': 2,
    'NODE_INDEX_STORE': 20,
    'NODE_INT': 7,
    'NODE_LET': 1,
    'NODE_LOOP': 3,
    'NODE_MATCH': 13,
    'NODE_PRINT': 14,
    'NODE_RET': 9,
    'NODE_STR': 8,
    'NODE_STRUCT': 11,
    'NODE_STRUCT_INIT': 17,
    'NODE_SYSCALL': 15,
    'N_ALLOC_REGS': 8,
    'OP_ADD': 1,
    'OP_ADDR': 23,
    'OP_ALLOC': 26,
    'OP_AND': 12,
    'OP_BR': 15,
    'OP_CALL': 17,
    'OP_CMP_EQ': 6,
    'OP_CMP_GT': 9,
    'OP_CMP_GTE': 10,
    'OP_CMP_LT': 8,
    'OP_CMP_LTE': 11,
    'OP_CMP_NE': 7,
    'OP_CONST': 0,
    'OP_DIV': 4,
    'OP_JMP': 16,
    'OP_LOAD': 22,
    'OP_LOAD_MEM': 24,
    'OP_MUL': 3,
    'OP_NEG': 5,
    'OP_OR': 13,
    'OP_PRINT_INT': 27,
    'OP_RET': 14,
    'OP_STORE': 21,
    'OP_STORE_MEM': 25,
    'OP_STRLEN': 20,
    'OP_STRLIT': 19,
    'OP_SUB': 2,
    'OP_SYSCALL': 18,
    'PHYS_R10': 10,
    'PHYS_R11': 11,
    'PHYS_R8': 8,
    'PHYS_R9': 9,
    'PHYS_RAX': 0,
    'PHYS_RBP': 5,
    'PHYS_RBX': 3,
    'PHYS_RCX': 1,
    'PHYS_RDI': 7,
    'PHYS_RDX': 2,
    'PHYS_RSI': 6,
    'PHYS_RSP': 4,
    'TOK_AMP': 32,
    'TOK_AND': 37,
    'TOK_ARROW': 22,
    'TOK_COLON': 20,
    'TOK_COMMA': 19,
    'TOK_CONST': 39,
    'TOK_DOT': 33,
    'TOK_ELSE': 3,
    'TOK_EOF': 40,
    'TOK_EQ': 23,
    'TOK_EQEQ': 24,
    'TOK_F64': 44,
    'TOK_FATARROW': 34,
    'TOK_FN': 0,
    'TOK_GT': 27,
    'TOK_GTE': 35,
    'TOK_I32': 42,
    'TOK_I64': 41,
    'TOK_I8': 43,
    'TOK_IDENT': 10,
    'TOK_IF': 2,
    'TOK_INT': 11,
    'TOK_LBRACE': 15,
    'TOK_LBRACK': 17,
    'TOK_LET': 1,
    'TOK_LOOP': 4,
    'TOK_LPAREN': 13,
    'TOK_LT': 26,
    'TOK_LTE': 36,
    'TOK_MATCH': 7,
    'TOK_MINUS': 29,
    'TOK_NEQ': 25,
    'TOK_OR': 38,
    'TOK_PLUS': 28,
    'TOK_PRINT': 8,
    'TOK_RBRACE': 16,
    'TOK_RBRACK': 18,
    'TOK_RET': 5,
    'TOK_RPAREN': 14,
    'TOK_SEMI': 21,
    'TOK_SLASH': 31,
    'TOK_STAR': 30,
    'TOK_STR': 12,
    'TOK_STRUCT': 6,
    'TOK_SYSCALL': 9,
    'TYPE_F64': 4,
    'TYPE_I32': 2,
    'TYPE_I64': 1,
    'TYPE_I8': 3,
    'TYPE_PTR': 5,
    'TYPE_PTR_FLAG': 0x10000,
    'TYPE_PTR_I32': 0x10002,
    'TYPE_PTR_I64': 0x10001,
    'TYPE_PTR_I8': 0x10003,
    'TYPE_VOID': 0,
}
